//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceItem
    {
        public int PriceItemId { get; set; }
        public Nullable<int> PriceId { get; set; }
        public string Description { get; set; }
    
        public virtual Price Price { get; set; }
    }
}
